import Header from './Header.js';

export default function TermsAndConditions() {
	return(
		<>
			<Header />
			<div className="bg-[#f8f8f8] py-[50px] px-[20px] sm:px-[50px] font-['Lexend']">
				<div className="max-w-[1000px] bg-white mx-auto shadow-xl rounded-[10px] py-[20px] px-[20px] sm:px-[30px] font-normal text-[#4e4e4e] leading-[30px]">
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] text-black">
					    Terms and conditions
					</div>
					<p>
					    This Online Services Agreement ("Agreement") is a legally binding contract between you and SSBA Innovations Ltd (referred to as "SSBA Innovations").
					</p>
					<p>
					    This Agreement governs your use of the following services:
					</p>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>The TaxBuddy Income Tax Return Filing Service</li>
					    <li>TaxBuddy Tax Planner</li>
					    <li>Tax Query and Scrutiny Application</li>
					    <li>Any additional TaxBuddy-related tax programs or services you choose, pay for, or use in connection with TaxBuddy's tax preparation products and related offerings.</li>
					</ul>
					<p>
					    By accepting this Agreement or accessing, using, or duplicating any part of the products and services, you agree to comply with the terms and conditions stated herein. If you do not agree to the terms, please refrain from accessing, downloading, or using any part of the products and services.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    1. License and Permitted Use
					</div>
					<p>
					    Under the terms and conditions outlined in this Agreement, and upon payment of all applicable fees, SSBA Innovations grants you a limited, non-exclusive, non-transferable license to access and use the Products and Services for preparing and electronically submitting ("e-filing") your tax return(s) (the "License"). Additional charges may apply for using the Products and Services for tasks such as e-filing tax returns, submitting Form 16 or 16(A), and preparing or submitting income tax returns.
					</p>
					<p>
					    This License permits access to the Products and Services only as specified in this Agreement and for the category of services you have paid for. You may use the Products and Services exclusively through SSBA Innovations' online platform at <a href="/" className="text-[blue]">https://wertconsultancy.in/</a> or any authorized third-party website designated by SSBA Innovations. The terms and conditions for accessing SSBA Innovations' website will also apply, and in the event of inconsistencies, the terms of this Agreement will take precedence regarding the subject matter addressed here.
					</p>
					<p>
					    The Products and Services are not to be used for providing tax advice or services to third parties. Before filing your tax returns, you are fully responsible for reviewing all relevant data, including Form(s) 16 or 16(A), and ensuring its accuracy and completeness. You must also validate any outcomes generated by using the Products and Services.
					</p>
					<p>
					    If you plan to use the Products and Services on behalf of others, you must obtain proper authorization to file tax returns for those individuals or entities.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    2. Eligibility to Use the Platform:
					</div>
					<p>
						You are eligible to use the platform if:
					</p>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        You must be at least 18 years old. If acting as a guardian for a minor, you must have the necessary authority to register or sign up on the platform and conduct transactions on their behalf.
					    </li>
					    <li>
					        You must be of legal age to enter into a binding contract, not restricted by applicable laws, and eligible to use the platform services. The company reserves the right to deny platform access to new users in case of scalability issues. Users previously suspended or removed from the platform are not eligible to use its services.
					    </li>
					    <li>
					        You agree to adhere to the Terms of Use, offer documents, investor application forms, mutual fund and investment account opening forms, Risk Disclosure documents, and any other information provided by you while using the platform services.
					    </li>
					</ul>
					<p>
					    You also confirm that any funds you invest originate from your own bank account (or the primary holder's account in the case of jointly held accounts), are legally earned, and are transferred through approved banking channels.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    3. Geographical Locations:
					</div>
					<p>
					    Please note that platform services may not be available in all geographic regions. Depending on your location, certain services offered by the Company or TaxBuddy may not be accessible to you. The Company and/or TaxBuddy reserve the exclusive right to determine the availability and eligibility of any platform services.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    4. Restrictions:
					</div>
					<p>
					    You are strictly prohibited from engaging in the following activities, either directly or indirectly:
					</p>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>Redistributing, selling, renting, loaning, or transferring the Products and Services or any associated rights to another person or entity.</li>
					    <li>
					        Using the Products and Services for purposes other than their intended use or for the benefit of third parties. This includes sharing the Products and Services through application service providers, outsourcing, service bureaus, or peer-to-peer or file-sharing networks. Furthermore, using the Products and Services to perform third-party services is prohibited. Should you engage in such activities, you agree to indemnify and defend SSBA Innovations and its Affiliates against any losses, claims, liabilities, settlements, or costs, including reasonable legal fees, resulting from such unauthorized use.
					    </li>
					    <li>Copying or duplicating the Products and Services by any method, including electronic means.</li>
					    <li>Removing proprietary notices, labels, or trademarks embedded within the Products and Services.</li>
					    <li>Attempting to access or derive the source code of the Products and Services.</li>
					    <li>Disabling or bypassing access control mechanisms or security processes associated with the Products and Services.</li>
					</ul>
					<p>
					    You are solely responsible for all usage of the Products and Services under your account and for ensuring compliance with this Agreement. Any violations, whether by you or others using the Products and Services through your account, will be your responsibility. SSBA Innovations retains all rights not explicitly granted to you under this Agreement.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    5. Intellectual Property Rights:
					</div>
					<p>
					    SSBA Innovations, its Affiliates, or its licensors are the rightful owners of the Products and Services. These are protected by Indian Intellectual Property Laws, including trademark and copyright laws, as well as international treaties. The ownership and all associated intellectual property rights remain exclusively with SSBA Innovations, its Affiliates, or licensors.
					</p>
					<p>
					    Using the Products and Services does not grant you any ownership rights in them or any derivative works or components. This Agreement does not provide you with rights, titles, or interests in any trademarks, service marks, logos, or trade names belonging to SSBA Innovations, its Affiliates, or licensors. You are prohibited from decompiling, disassembling, modifying, reverse engineering, attempting to extract source code, or creating derivative works from the Products and Services or any part thereof.
					</p>
					<p>
					    SSBA Innovations and its Affiliates retain exclusive copyright ownership of the Products and Services. This includes the sole rights to create derivative works, duplicate, distribute, license, or sell the Products and Services.
					</p>
					<p>
					    You agree and acknowledge that the Products and Services, including any updates, corrections, enhancements, or modifications (irrespective of who makes these changes), as well as all associated copyrights, patents, trade secrets, trademarks, and other intellectual property rights, are and will remain the exclusive property of SSBA Innovations, its Affiliates, or its licensors.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Privacy:
					</div>
					<p>
					    Your use of the Products and Services is governed by SSBA Innovations' Privacy Notice, which can be accessed in full at <a href="/privacy-policy" className="text-[blue]">Privacy Notice.</a> SSBA Innovations reserves the right to modify the Privacy Notice and its associated policies in compliance with applicable laws. In the event of significant changes to the Privacy Notice, SSBA Innovations will notify you through one of the following methods:
					</p>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>A notice describing the change will be posted on the SSBA Innovations website.</li>
					    <li>An email notification about the change will be sent to you.</li>
					</ul>
					<p className="mt-[10px]">
					    When using the Products and Services, you may be required to provide certain details for preparing your tax return ("Tax Information") as well as other personal information. If you use the automatic tax information import feature to retrieve data from financial institutions or financial software, you are responsible for verifying the accuracy of the imported Tax Information.
					</p>
					<p>
					    If you e-file your tax return, SSBA Innovations will collect and transmit your Tax Information to the Income Tax Department in the appropriate electronic format. Additionally, SSBA Innovations will retain an electronic copy of your Tax Information, along with other personal details such as e-filing information and status, as required or permitted by law.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Non-availability of Electronic Filing:
					</div>
					<p>
					    You acknowledge and agree that e-filing may not be available in certain situations. SSBA Innovations does not guarantee the performance of the Internet, any third-party system, or the receipt, acceptance, or processing of your tax return by the Income Tax Department (ITD). SSBA Innovations' responsibility is limited to making reasonable efforts to electronically transmit your tax return to the ITD, provided you choose e-filing, meet the eligibility criteria, and pay all applicable fees.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Online Assisted Service:
					</div>
					<p>
					    SSBA Innovations may provide additional tax return preparation services as part of its Online Assisted Service. These services include offering tax advice, preparing your tax return, and electronically filing it with the Income Tax Department (ITD) as per your instructions.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Automatic Importing of Tax Information:
					</div>
					<p>
					    The Products and Services may offer a feature that enables you to electronically import specific Tax Information directly into the software. However, SSBA Innovations does not guarantee the availability or accuracy of this automatic import functionality.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Accurate Calculations Guarantee:
					</div>
					<p>
					    Under certain conditions, SSBA Innovations agrees to reimburse you for penalties and interest paid in relation to your FY 2017-18 tax return, up to the total amount of fees paid to SSBA Innovations. This reimbursement applies only if the penalties and interest were incurred solely due to:
					</p>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>An arithmetic error caused by the Software.</li>
					    <li>Incorrect advice provided to you as part of the Online Assisted Service.</li>
					</ul>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Qualifications for Reimbursement:
					</div>
					<p>
					    To qualify for reimbursement under this section, you must fulfill the following conditions:
					</p>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>The penalty and interest must pertain to your FY 2017-18 tax return.</li>
					    <li>
					        The penalty or interest must not result from any errors or omissions on your part, including incorrect data entry by you or a third party, data improperly imported into the Software, failure to follow Software instructions, failure to correct errors identified by the Software, unsupported claims for deductions, unreported income, failure to provide necessary information to SSBA Innovations, or incorrect interpretation of tax laws. It also must not result from any cause beyond SSBA Innovations' control.
					    </li>
					    <li>
					        You must notify SSBA Innovations promptly upon discovering the error, and no later than 30 days after the penalty or interest is assessed or you receive a notice from the ITD regarding your tax return, whichever is earlier. You must also provide SSBA Innovations with complete documentation, including all correspondence with the ITD, a copy of your filed tax return, proof of penalty and interest payment, and any other requested information.
					    </li>
					    <li>
					        You must take any reasonable actions requested by SSBA Innovations, such as filing an amended tax return, to prevent additional penalties and interest from accruing.
					    </li>
					    <li>
					        The penalty and interest must be for a return filed on or before July 31, 2018, or within any extended filing deadline set by the ITD.
					    </li>
					    <li>
					        You must comply with all terms and conditions of this Agreement, including license restrictions, and you must not have provided any false information during account registration or tax return preparation.
					    </li>
					    <li>
					        You must have paid any applicable fees to SSBA Innovations for the Software license and any related Products and Services at the time of filing your tax return.
					    </li>
					    <li>
					        The penalty or interest must not result from knowingly following incorrect advice from SSBA Innovations at the time of filing your return.
					    </li>
					    <li>
					        Your tax return must have been prepared using the FY 2017-18 version of the Software and in compliance with this Agreement and its operating instructions.
					    </li>
					</ul>
					<p>
					    This section outlines SSBA Innovations' entire liability and your sole remedy for any errors in your tax return caused by the Products and Services or SSBA Innovations. Monetary remedies under this section are void if you request a refund for the Software as described in Section 7 of this Agreement. The rights and benefits provided in this section are personal and non-transferable to other parties.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Disclaimer of Warranties:
					</div>
					<p>
					    Except as expressly stated in this agreement, SSBA Innovations provides no additional warranties, whether express or implied, regarding the Products and Services. To the fullest extent allowed by applicable law, all implied warranties, including but not limited to those of non-infringement, merchantability, and fitness for a specific purpose, are excluded from your use of the Products and Services.
					</p>
					<p>
					    SSBA Innovations does not guarantee that the Products and Services will identify the correct documents for your needs or be free from bugs or errors. Additionally, SSBA Innovations makes no assurances about the performance, accuracy, or reliability of the Products and Services or their ability to meet your requirements. The Products and Services are intended as general tools to assist with tax preparation and filing but do not eliminate your responsibility to exercise independent judgment. You are fully responsible for entering accurate information and verifying the results generated by the Products and Services. SSBA Innovations, its affiliates, and franchisees do not guarantee specific outcomes from your use of the Products and Services.
					</p>
					<p>
					    You understand that SSBA Innovations and its licensors do not practice law and do not provide legal or professional advice. Your use of the Products and Services is not a replacement for consultation with a qualified legal or professional advisor. Laws differ and may change over time, and final documents, forms, and correspondence should be reviewed by a legal or other qualified professional before being used.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[10px] mt-[30px] text-black">
					    Consent to Electronic Communications:
					</div>
					<p>
					    This consent to electronic communications is provided in accordance with the Information Technology Act 2000 and confirms your agreement to receive all Required Disclosures electronically related to your use of the Products and Services. "Required Disclosures" include all notices, communications, disclosures, or other legally required information pertaining to your use of the Products and Services.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Scope of Consent:
					</div>
					<p>
					    Your consent to receive Required Disclosures electronically applies to all such communications related to your use of the Products and Services and your relationship with SSBA Innovations.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Consent:
					</div>
					<p>
					    You consent to receive Required Disclosures electronically and acknowledge that SSBA Innovations is not required to provide additional paper copies of the Required Disclosures unless specifically requested, as outlined above. By opting into the email/SMS alert service, you grant SSBA Innovations a non-exclusive, irrevocable right to send emails, SMS messages, and alerts at their discretion.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Payments:
					</div>
					<p>
					    As a merchant, we are not responsible for any loss or damage resulting directly or indirectly from the denial of authorization for a transaction due to the Cardholder exceeding the pre-set limit agreed upon between us and our acquiring bank.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Refund Policy:
					</div>
					<p>
					    The Refund & Cancellation policy for all payments made toward account opening or any other services or products through any payment method is as follows:
					</p>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        Fees paid for account opening charges related to mutual funds, wealth builder services, tax planning services (Financial planning on TaxBuddy.com), or any other services are non-refundable and non-reimbursable.
					    </li>
					    <li>
					        The collection of documents, forms, or deeds required for the account opening process depends on the availability of our representatives at specific times and locations.
					    </li>
					    <li>
					        If your account is not opened by Team TaxBuddy within ten days after all necessary documents and authorizations have been submitted, you may request a full refund of the charges paid for account activation.
					    </li>
					    <li>
					        If you have been charged multiple times for account opening, please contact our support team to initiate the refund process.
					    </li>
					</ul>
					<p>
					    Note: The completion and execution of the refund process are subject to the policies and procedures of third parties such as banks and payment gateways.
					</p>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Security:
					</div>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        You agree to take adequate security measures to safeguard your passwords and user IDs associated with the Products and Services. These measures should be at least as robust as those used to secure your own computer equipment, software, and online financial accounts, and they must not fall below a standard of reasonable and prudent care.
					    </li>
					    <li>
					        You must notify SSBA Innovations immediately if you become aware of any unauthorized use of your user ID or password, any misuse of the Products and Services, or any other security breach.
					    </li>
					    <li>
					        You are solely responsible for maintaining the confidentiality of your account number, user ID, password, and other sensitive information. You acknowledge and accept full responsibility for all aspects of computer, data, file, and network security, which includes ensuring that your computer or network connection is equipped with an active firewall, anti-virus software, and anti-spyware software. These measures are essential to secure and protect any proprietary or confidential information you provide, store, submit, transmit, or disclose during your use of the Products and Services.
					    </li>
					</ul>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Posts:
					</div>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        The Company and/or TaxBuddy may feature content on the Platform that includes articles or write-ups from third parties about mutual funds and stocks. You acknowledge and agree that this content does not reflect the views or recommendations of the Company and/or TaxBuddy. It is your responsibility to carefully review all documents before making any investments in mutual funds or stocks.
					    </li>
					    <li>
					        You may have the ability to post and comment on such content on the Platform. You agree to ensure that your comments are not offensive and comply with all applicable laws.
					    </li>
					    <li>
					        Any material you add, create, submit, or post to the Platform is solely your responsibility. The Company and/or TaxBuddy reserves the right to review the information or data you upload and remove any content that violates these Terms of Use.
					    </li>
					</ul>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Dispute Resolution:
					</div>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        Both parties agree that any disputes arising from or related to this Agreement, or to the Products and Services provided under it, will fall under the exclusive jurisdiction of the courts in Mumbai, India.
					    </li>
					    <li>
					        In case of any dispute following the provision of the ITR filing service, TaxBuddy’s liability for compensation will be strictly limited to the amount paid for the service.
					    </li>
					</ul>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Indemnification:
					</div>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        You agree to indemnify and defend SSBA Innovations, along with its current and former successors, assigns, officers, directors, representatives, employees, and agents, against any claims, lawsuits, settlements, losses, liabilities, penalties, damages (including incidental and consequential damages), costs, and expenses (including reasonable attorneys' fees and expenses) that arise from or result due to your breach of this Agreement.
					    </li>
					</ul>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Termination:
					</div>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        Without limiting any other rights, SSBA Innovations reserves the right to terminate this Agreement immediately if you fail to comply with its terms and conditions. In such an event, you must promptly discontinue the use and access to the Products and Services, destroy all copies of the Products and Services in your possession, and provide written confirmation to SSBA Innovations verifying your compliance with this requirement.
					    </li>
					</ul>
					<div className="text-[24px] sm:text-[30px] font-semibold mb-[5px] mt-[30px] text-black">
						Calling, SMS & WhatsApp Policy:
					</div>
					<ul className="list-disc pl-[30px] sm:pl-[50px]">
					    <li>
					        You consent to the electronic delivery of Required Disclosures and acknowledge that SSBA Innovations is not obligated to provide a non-electronic copy unless specifically requested, as outlined above. By opting into call, email, SMS, or WhatsApp alert services, you grant SSBA Innovations a non-exclusive, irrevocable right to contact you via calls, emails, SMS, WhatsApp messages, and alerts, regardless of whether your numbers are registered on the National Do Not Call Registry or listed in the National Customer Preference Register. 
					        <br />
					        You further agree that SSBA Innovations or its third-party service providers will not be held liable or subject to complaints under the Telecom Commercial Communications Customer Preference (TRAI) Regulations, 2010, or any applicable amendments, for sending such communications.
					    </li>
					</ul>
				</div>
			</div>
		</>
	)
}


